name: Dialyzer

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  dialyzer:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: ci
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: true
      matrix:
        include:
          - pair:
              otp: 25
              elixir: 1.14
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get --only ci
      - name: Run Dialyzer
        run: |
          mix quality.ci
